### ISSUE TITLE
Follow links

### ISSUE THREAD

**Issue by Reikimann** [charmbracelet/glow#352] opened 2022-06-20 08:46 UTC
Hello Devs

Please make it possible to follow both filesystem links (/foo/bar) and weblinks. It would make the experience feel more
complete. For example the [TuxDocs](https://github.com/Reikimann/TuxDocs/tree/Readme-edits) project. Being able to follow the links inside the terminal would be awesome!

**Comment by muesli** [comment] 2022-10-12 00:04
If I understand you correctly, this looks like a dupe of #237. We're working on some improvements!

**Closed by muesli** 2022-10-12 00:04 UTC
Labels: duplicate
