### ISSUE TITLE
[enhancement] add file monitor support

### ISSUE THREAD

**Issue by sww1235** [charmbracelet/glow#155] opened 2020-09-05 18:05 UTC
I like using glow to see an output preview of my markdown files, however it would be nice to have a flag that will detect changes to the open file and reload the file into glow while it is opened in a pager.

**Comment by muesli** [comment] 2020-10-15 04:55
Good idea, but I think we can file this as a duplicate of #148.

**Closed by muesli** 2020-10-15 04:55 UTC
Labels: duplicate

**Comment by sww1235** [comment] 2020-10-15 12:42
Woops, didn't even notice. Thanks 👍
