### ISSUE TITLE
Charm colourscheme does not work within tmux

### ISSUE THREAD

**Issue by OliverFM** [charmbracelet/glow#310] opened 2021-12-10 17:47 UTC
I am loving using glow, but when I run it inside Tmux the colour scheme is mangled.

I am running MacOS big sur, in Iterm2 with the solarized dark scheme. I have added `set -g default-terminal "screen-256color"` to my `.tmux.conf` but, sadly, that does not fix the problem. Nor does setting `glow -s dark`.

Any suggestions?
<img width="570" alt="Screenshot 2021-12-10 at 19 44 45" src="https://user-images.githubusercontent.com/16237233/145618275-0dfe4041-e4f0-4ba4-9c24-f69a117f559e.png">
!

**Comment by meowgorithm** [comment] 2021-12-10 18:24
Hi! I'm not able to reproduce this in iTerm2 in tmux on macOS at all (I tried both with the tmux default settings as well as `set -g default-terminal "screen-256color"`).

Based on the screenshot it looks like this may be an issue with background color detection. So we can investigate, what is the exact color your background is set to?

**Comment by OliverFM** [comment] 2021-12-10 18:28
> Hi! I'm not able to reproduce this in iTerm2 in tmux on macOS at all (I tried both with the tmux default settings as well as `set -g default-terminal "screen-256color"`).
> 
> Based on the screenshot it looks like this may be an issue with background color detection. So we can investigate, what is the exact color your background is set to?

Thanks for the reply, I am using [solarized dark](https://ethanschoonover.com/solarized/) -- I _think_ that the version I have is prepackaged with iTerm2

**Comment by OliverFM** [comment] 2021-12-14 14:45
This issue doesn't show up when I switch to Solarized Light.
And running `glow -s dark README` fixes the issue with solarized dark. So I imagine that I need to set some env var for glow to pick this up automatically. 
Any ideas what this might be, @meowgorithm?

**Comment by muesli** [comment] 2021-12-14 16:39
@OliverFM This issue is tricky, as within tmux there's no actual way to communicate with the terminal and query its current color setting (as there might be multiple terminals with different color settings connected to the same tmux session). As such I assume your current setting gets picked up from the `COLORFGBG` environment variable. Could you check if that's set and what its value is?

**Comment by meowgorithm** [comment] 2021-12-14 17:17
(Side note @OliverFM: in the meantime you can run set the default style to `dark`. Run `glow config` to open the config in your `EDITOR`.)

**Comment by OliverFM** [comment] 2021-12-15 10:27
Thanks for the updates!
I am getting:
```
❯ echo $COLORFGBG
12;8
```
in my dark shell and 
```
❯ echo $COLORFGBG
11;15
```
in the light one

**Comment by Diablo-D3** [comment] 2022-07-14 02:18
This looks identical to if I executed `glow -s light`. I suspect iTerm2 is saying (via `$COLORFGBG` or `OSC 11`) that you're on a light terminal theme.

I have not used a Mac in almost a decade, but last time I did, I used iTerm2, and vaguely remember this being an issue with other apps that were theme brightness aware.

The fix is to configure iTerm2 to say you're on a dark theme.

**Comment by muesli** [comment] 2022-10-12 00:33
Thanks for the insight @Diablo-D3! Closing as it looks like there's not much we can fix on our end.

**Closed by muesli** 2022-10-12 00:33 UTC
