### ISSUE TITLE
glow --all doesnt work

### ISSUE THREAD

**Issue by alexzanderr** [charmbracelet/glow#285] opened 2021-08-02 14:18 UTC
i have a folder which is git ignored, in that folder there are some markdowns that i want to see using glow --all but not be available for github.

some people said that `glow --all` would be a solution, unfortunatelly it isnt.

**Comment by muesli** [comment] 2021-08-05 17:34
You're right, `--all` still ignores everything in `.gitignore`. We should probably change that, otherwise `all` is a bit of a misnomer.

**Comment by alexzanderr** [comment] 2021-08-05 18:28
thanks for response

**Comment by uncomfyhalomacro** [comment] 2023-02-22 05:35
any news on fixing? i was surprised that it cannot show my gitignored markdown files and folders with `glow --all`.

**Comment by JammUtkarsh** [comment] 2023-05-12 12:28
Hey @muesli,
I'm interested in contributing to the issue. If the issue is still not fixed, I'll appreciate any information you can provide to fix.

Looking forward to contributing to the project!
Utkarsh Chourasia

**Comment by aitva** [comment] 2023-05-26 13:48
I have a `.gitignore` in my home directory that excludes everything. It allows me to [track my dotfiles easily](https://drewdevault.com/2019/12/30/dotfiles.html), but also prevent me from using Glow.

**Comment by jjspace** [comment] 2024-02-02 16:45
Any updates on this? I was trying to explore a new repo that generates documentation using md files but they're in the `.gitignore` because they're created as part of the build system. This meant that `glow` was useless even if I pointed it directly at the file I wanted to open.

**Comment by caarlos0** [comment] 2024-07-03 16:44
this is fixed on master.

thanks for the issue, sorry for the delay!

**Closed by caarlos0** 2024-07-03 16:44 UTC
Labels: enhancement
