### ISSUE TITLE
Is it possible to open links?

### ISSUE THREAD

**Issue by NullSense** [charmbracelet/glow#174] opened 2020-10-18 09:36 UTC
Is it possible to somehow follow links? I have a lot of notes that are linked to each other (Zettelkasten style) and was wondering if I could use this viewer to render them.

**Comment by muesli** [comment] 2022-10-12 00:20
It's tricky because only a few terminals support link markup through OSC8, but it's something we're working on. Even though your ticket was technically first, I'm gonna close this as a dupe of #237 where we'll track the progress.

**Closed by muesli** 2022-10-12 00:20 UTC
Labels: duplicate
