### ISSUE TITLE
Unable to locate package glow

### ISSUE THREAD

**Issue by Daydream0929** [charmbracelet/glow#556] opened 2024-01-11 04:11 UTC
**Describe the bug**
I can't install the glow from apt-get on ubuntu22.04LTS

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS [Ubuntu 22.04 LTS]
 - Shell [bash]

**To Reproduce**
1. install from sudo apt
2. see the error

**Source Code**
bash
```
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
sudo apt update && sudo apt install glow
```

**Screenshots**
![image](https://github.com/charmbracelet/glow/assets/61659904/75db5ad4-cdab-47f7-8c7b-6b8ce9f1ca20)

**Comment by mirsahebali** [comment] 2024-02-14 05:00
Hey is the problem seems to be resolved? 
I tried to reproduce on a fresh Ubuntu 22.04LTS installation and it seems to be working and it gets installed with the command you have given above. 
Try to run each command individually and see if it works this time.

**Comment by caarlos0** [comment] 2024-07-03 16:21
this was probably an issue with our provider (fury.io), should be fixed.

thanks!

**Closed by caarlos0** 2024-07-03 16:21 UTC
