### ISSUE TITLE
So it is not a markdown reader yet?

### ISSUE THREAD

**Issue by AndyJado** [charmbracelet/glow#390] opened 2022-10-08 04:22 UTC
Since I don't get to read a markdown file not seeing those markups.

So this is not a `markdown-reader-in-terminal` ?

**Comment by muesli** [comment] 2022-10-08 04:34
It is. Which markups are you not seeing?

**Comment by AndyJado** [comment] 2022-10-08 05:37
pardon my toes and tongue

by markups I mean `#` `url address` `*`, especially the url adress.

I don't think I should see them when I want to **read** a markdown file.

**Comment by muesli** [comment] 2022-10-08 12:39
Can you post a screenshot of what's bothering you, I'm not sure I fully understand yet.

**Comment by AndyJado** [comment] 2022-10-09 13:36
[this is proper markdown reading](https://github.com/charmbracelet/glow/issues/390)

```
[this is not a markdown reader](https://github.com/charmbracelet/glow/issues/390)
```

**Comment by muesli** [comment] 2022-10-12 00:00
The issue is that not all terminals support OSC8 which allows for link markup. We're working on improving that situation however: https://github.com/muesli/termenv/commit/e706a87c011eba65893f94d6764974eec56bf223

**Comment by muesli** [comment] 2022-10-12 00:01
Closing as dupe of #352.

**Closed by muesli** 2022-10-12 00:01 UTC
Labels: duplicate
